const express = require("express");
const nodemailer = require("nodemailer");
const bodyParser = require("body-parser");
const cors = require("cors");
require("dotenv").config();

const app = express();
const port = process.env.PORT || 3000;

app.use(bodyParser.json());
app.use(cors({
    origin: "*",
    methods: "GET,HEAD,PUT,PATCH,POST,DELETE",
    preflightContinue: false,
    optionsSuccessStatus: 204
}));

let transporter = nodemailer.createTransport({
  host: "smtp.gmail.com",
  port: 465,
  secure: true,
  service: "gmail",
  auth: {
    user: process.env.USER,
    pass: process.env.PASS,
  },
});

app.post("/sendmail", async (req, res) => {
  const message = req.body.message;
  const name = req.body.name;
  const senderEmail = req.body.email;

  let mailOptionsToOrg = {
    from: name,
    to: process.env.ORG_EMAIL,
    subject: "Website Contact Message from " + name,
    replyTo: senderEmail,
    html: `<!DOCTYPE html>
            <html>
            <head>
                <style>
                    body {
                        font-family: Arial, sans-serif;
                        line-height: 1.6;
                        margin: 0;
                        padding: 0;
                        background-color: #f4f4f4;
                        color: #333;
                    }
                    .container {
                        width: 90%;
                        max-width: 600px;
                        margin: 20px auto;
                        background: #fff;
                        padding: 20px;
                        border-radius: 8px;
                        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
                    }
                    .header {
                        text-align: center;
                        background-color: #4285F4;
                        color: white;
                        padding: 10px;
                        border-radius: 8px 8px 0 0;
                    }
                    .header h1 {
                        margin: 0;
                        font-size: 20px;
                    }
                    .content {
                        padding: 20px;
                    }
                    .content p {
                        margin: 15px 0;
                    }
                    .footer {
                        text-align: center;
                        padding: 10px;
                        background-color: #f9f9f9;
                        border-top: 1px solid #ddd;
                        border-radius: 0 0 8px 8px;
                    }
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <h1>Website Contact Message</h1>
                    </div>
                    <div class="content">
                        <p><strong>Name:</strong> ${name}</p>
                        <p><strong>Email:</strong> ${senderEmail}</p>
                        <p><strong>Message:</strong></p>
                        <p>${message}</p>
                    </div>
                    <div class="footer">
                        <p>This email was automatically generated by your contact form. Please reply if necessary.</p>
                    </div>
                </div>
            </body>
            </html>`,
  };

  let mailOptionsToSender = {
    from: process.env.ORG_EMAIL,
    to: senderEmail,
    subject: "Thank You for Contacting GDSC IIITA",
    replyTo: process.env.ORG_EMAIL,
    html: `<!DOCTYPE html>
        <html>
        <head>
            <style>
                body {
                    font-family: Arial, sans-serif;
                    line-height: 1.6;
                    margin: 0;
                    padding: 0;
                    background-color: #f4f4f4;
                    color: #333;
                }
                .container {
                    width: 90%;
                    max-width: 600px;
                    margin: 20px auto;
                    background: #fff;
                    padding: 20px;
                    border-radius: 8px;
                    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
                }
                .header {
                    text-align: center;
                    background-color: #34A853;
                    color: white;
                    padding: 10px;
                    border-radius: 8px 8px 0 0;
                }
                .header h1 {
                    margin: 0;
                    font-size: 20px;
                }
                .content {
                    padding: 20px;
                }
                .content p {
                    margin: 15px 0;
                }
                .footer {
                    text-align: center;
                    padding: 10px;
                    background-color: #f9f9f9;
                    border-top: 1px solid #ddd;
                    border-radius: 0 0 8px 8px;
                }
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>Thank You for Contacting GDSC IIITA!</h1>
                </div>
                <div class="content">
                    <p>Hi ${name},</p>
                    <p>Thank you for reaching out to us! We have received your message and will get back to you shortly.</p>
                    <p><strong>Your Message:</strong></p>
                    <p>${message}</p>
                </div>
                <div class="footer">
                    <p>If you have any additional questions, feel free to reply to this email.</p>
                    <p>Best regards,<br>GDSC IIITA Team</p>
                </div>
            </div>
        </body>
        </html>`,
  };

  try {
    await transporter.sendMail(mailOptionsToOrg);
    console.log("Email sent to GDSC IIITA");

    await transporter.sendMail(mailOptionsToSender);
    console.log("Email sent to Sender");

    res.status(200).send("Emails sent successfully!");
  } catch (error) {
    console.log("Error occurred:", error);

    res.status(500).send("Failed to send emails.");
  }
});

app.listen(port, () => {
  console.log(`listening at http://localhost:${port}`);
});
